'use strict';
const $ = id => document.getElementById(id);
let state, csrf='', latestAudio=null, messageKey='', eventKey='', initialized=false, pollBusy=false;
let toastTimer;
function toast(text,error=false){$('toast').textContent=text;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?8000:4000)}
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Fuzozo-Token':csrf},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function action(kind,payload={}){try{const result=await post('/api/action',{kind,payload});toast(kind==='connect'?'Checking connection…':'Request queued');await refresh();return result.job_id}catch(e){toast(e.message,true)}}
function dot(id,status){$(id).className='status-dot '+status}
function messageNode(m){const row=document.createElement('div');row.className='chat-message '+m.role;const label=document.createElement('span');label.className='message-label';label.textContent=m.role==='user'?(m.source==='voice'?'YOU · VOICE':'YOU'):(state.settings.agent_name||'LAB COMPANION');const bubble=document.createElement('div');bubble.className='message-bubble';bubble.textContent=m.text;row.append(label,bubble);const job=state.jobs.find(j=>j.id===m.job_id);if(job?.audio_url){const replay=document.createElement('button');replay.className='text-button message-play';replay.textContent='Replay on Fuzozo ↗';replay.onclick=()=>action('replay',{job_id:m.job_id});row.append(replay)}return row}
function render(s){state=s;csrf=s.csrf;dot('server-dot','good');$('server-label').textContent='Running on this Mac';const connected=s.device.verified&&s.device.adapter_present;const available=s.device.candidates.length>0;const deviceLabel=connected?'Fuzozo connected':available?'USB found · check connection':'Waiting for Fuzozo';$('device-state').textContent=deviceLabel;const d=$('device-pill').querySelector('.status-dot');d.className='status-dot '+(connected?'good':'warn');$('connection-detail').textContent=connected?'USB connected · '+(s.device.muted?'sound muted':'volume '+s.device.volume+'%'):'Keep Fuzozo awake and connected by USB.';
 $('connect').disabled=s.jobs.some(j=>j.kind==='connect'&&['queued','running'].includes(j.status));$('connect').lastChild.textContent=connected?' Check connection':' Connect Fuzozo';
 const labels={idle:'READY',connecting:'CONNECTING',volume:'SOUND',synthesizing:'MAKING VOICE',thinking:'THINKING',speaking:'SPEAKING',listening:'LISTENING',recognizing:'RECOGNIZING',preparing:'PREPARING',error:'NEEDS ATTENTION'};$('phase-label').textContent=labels[s.phase]||s.phase.toUpperCase();$('notice').textContent=s.notice;dot('work-dot',s.phase==='error'?'bad':s.phase==='idle'?'good':'warn');const q=s.jobs.filter(j=>j.status==='queued').length;$('queue-count').textContent=q?q+' queued':'';
 dot('ai-dot',s.services.studio==='ready'?'good':'warn');$('ai-status').textContent=s.services.studio==='ready'?'AI SERVER':s.services.studio.toUpperCase();
 $('master-volume').disabled=!connected;$('mute').disabled=!connected;if(document.activeElement!==$('master-volume')&&s.device.volume!==null){$('master-volume').value=s.device.volume;$('master-value').textContent=s.device.volume+'%'}$('mute').setAttribute('aria-pressed',s.device.muted?'true':'false');$('sound-notice').hidden=!s.device.muted&&s.device.volume!==0;if(!$('sound-notice').hidden)$('sound-notice').textContent='The robot is muted. Unmute it to hear speech and AI replies.';
 if(document.activeElement!==$('speech-volume')){$('speech-volume').value=s.settings.speech_level;$('speech-value').textContent=s.settings.speech_level+'%'}
 $('voice-toggle').disabled=!connected&&!s.voice.enabled;const listening=s.voice.state==='listening';$('listen-visual').classList.toggle('active',listening);$('voice-toggle').querySelector('span').textContent=s.voice.enabled?'Stop listening':'Start listening';$('voice-toggle').setAttribute('aria-pressed',String(s.voice.enabled));$('voice-detail').textContent=s.voice.enabled?({listening:'Listening through Fuzozo’s microphone.',recognizing:'Recognizing your question…',replying:'Preparing the answer. Listening resumes afterward.',starting:'Starting the microphone…'}[s.voice.state]||s.voice.state):'Listening pauses while the companion replies.';$('listen-help').textContent='Say “'+s.settings.wake_word[0].toUpperCase()+s.settings.wake_word.slice(1)+'”, then your question. Uses Fuzozo’s own microphone.';
 if(!initialized){$('agent-name').value=s.settings.agent_name;$('reply-style').value=s.settings.reply_style;$('instructions').value=s.settings.instructions;$('wake-word').value=s.settings.wake_word;initialized=true}
 const mk=JSON.stringify([s.messages,s.jobs.filter(j=>j.audio_url).map(j=>j.id),s.settings.agent_name]);if(mk!==messageKey){messageKey=mk;if(s.messages.length){$('conversation').replaceChildren(...s.messages.map(messageNode));$('conversation').scrollTop=$('conversation').scrollHeight}else if($('conversation').querySelector('.chat-message')){$('conversation').replaceChildren();const p=document.createElement('p');p.className='helper';p.textContent='Conversation cleared. Say hello to start again.';$('conversation').append(p)}}
 const audio=s.jobs.filter(j=>j.audio_url).at(-1);if(audio&&audio.id!==latestAudio){latestAudio=audio.id;$('audio-preview').hidden=false;$('audio-player').src=audio.audio_url;$('audio-description').textContent=(audio.text||audio.answer||'Speech preview')+' · '+audio.seconds+' seconds'}
 const ek=JSON.stringify([s.events,s.jobs.filter(j=>j.status==='error'||j.status==='cancelled').map(j=>j.id)]);if(ek!==eventKey){eventKey=ek;const events=s.events.slice(-8).reverse();$('activity-list').replaceChildren(...events.map(e=>{const row=document.createElement('div');row.className='activity-row '+e.kind;const dot=document.createElement('span');dot.className='status-dot '+(e.kind==='error'?'bad':e.kind==='warning'?'warn':'good');const text=document.createElement('span');text.className='event-text';text.textContent=e.text;const date=document.createElement('time');date.dateTime=e.at;date.textContent=new Date(e.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});row.append(dot,text,date);return row}))}
}
async function refresh(){if(pollBusy)return;pollBusy=true;try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error('Panel unavailable');render(await r.json())}catch(e){dot('server-dot','bad');$('server-label').textContent='Service unavailable';$('phase-label').textContent='OFFLINE';$('notice').textContent='Open Start Fuzozo Panel.command to reconnect.'}finally{pollBusy=false}}
$('speech-text').addEventListener('input',()=>{$('speech-count').textContent=$('speech-text').value.length+' / 600'});
$('speak').onclick=()=>{const text=$('speech-text').value.trim();if(!text)return toast('Enter something for Fuzozo to say.');action('speak',{text})};$('preview').onclick=()=>{const text=$('speech-text').value.trim();if(!text)return toast('Enter some text to preview.');action('preview',{text})};$('replay').onclick=()=>latestAudio&&action('replay',{job_id:latestAudio});$('connect').onclick=()=>action('connect');
$('chat-form').onsubmit=e=>{e.preventDefault();const text=$('chat-text').value.trim();if(!text)return;action('ask',{text,speak:$('speak-replies').checked}).then(id=>{if(id)$('chat-text').value=''})};$('chat-text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('chat-form').requestSubmit()}};$('clear-chat').onclick=()=>action('clear_chat');
$('master-volume').oninput=()=>{$('master-value').textContent=$('master-volume').value+'%'};$('master-volume').onchange=()=>action('volume',{level:Number($('master-volume').value)});$('mute').onclick=()=>action('volume',{muted:!state.device.muted});$('speech-volume').oninput=()=>{$('speech-value').textContent=$('speech-volume').value+'%'};$('speech-volume').onchange=async()=>{try{await post('/api/settings',{speech_level:Number($('speech-volume').value)});toast('Speech level saved')}catch(e){toast(e.message,true)}};
$('voice-toggle').onclick=async()=>{try{await post('/api/voice',{enabled:!state?.voice.enabled});await refresh()}catch(e){toast(e.message,true)}};$('stop-all').onclick=async()=>{try{await post('/api/stop',{});toast('Stopping safely after the current hardware operation.');await refresh()}catch(e){toast(e.message,true)}};
$('settings-form').onsubmit=async e=>{e.preventDefault();try{await post('/api/settings',{agent_name:$('agent-name').value.trim(),reply_style:$('reply-style').value,wake_word:$('wake-word').value.trim(),instructions:$('instructions').value.trim()});toast('Companion settings saved');await refresh()}catch(e){toast(e.message,true)}};
document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(n=>n.classList.remove('active'));link.classList.add('active')}));$('today').textContent=new Date().toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'});refresh();setInterval(refresh,1200);
